// Vue/vuepracticaslunes/src/components/CollatzComponent.vue
<template>
  <div>
    <label>Introduce número para la conjetura de Collatz</label><br />
    <input type="number" v-model="numero" />
    <button @click="getConjetura()">Mostrar conjetura</button>
    <div v-if="secuencia.length > 0">
      <span
        v-for="num in secuencia"
        :key="num"
        v-html="$filters.getDibujo(num)"
      ></span>
    </div>
  </div>
</template>

<script>
export default {
  name: "CollatzComponent",
  methods: {
    getConjetura() {
      var num = this.numero;
      this.secuencia = [];
      while (num !== 1) {
        if (num % 2 === 0) {
          num = num / 2;
        } else {
          num = num * 3 + 1;
        }
        this.secuencia.push(num);
      }
      return this.secuencia;
    },
  },
  data() {
    return {
      secuencia: [],
      numero: 0,
    };
  },
};
</script>

// React/reactformsrutas/src/components/Collatz.js
import React, { Component } from 'react'

export default class Collatz extends Component {
    // Necesitamos un objeto caja para recuperar el dato
    cajaNumero = React.createRef();
    state = {
        secuencia: []
    }
    
    formulario = (e) => {
        e.preventDefault();
        let numero = parseInt(this.cajaNumero.current.value);
        const nuevaSecuencia = []
        // Si se quiere añadir el número de la secuencia
        // nuevaSecuencia.push(numero);
        while (numero !== 1) {
            if (numero % 2 === 0) {
                numero = numero / 2;
            } else {
                numero = (numero * 3) + 1;
            }
            nuevaSecuencia.push(numero);
        }
        this.setState({
            secuencia: nuevaSecuencia
        })
    }
    
    render() {
        return (
            <div>
                <h1>Conjetura de Collatz</h1>
                <form onSubmit={this.formulario}>
                    <label>Número de la secuencia</label>
                    <input type="text" ref={this.cajaNumero}></input>
                    <button>Ver secuencia</button>
                </form>
                {
                    this.state.secuencia.length > 0 &&
                    (
                        <ul>
                            {
                                this.state.secuencia.map((num, index) => (
                                    <li key={index}>{num}</li>
                                ))
                            }
                        </ul>
                    )
                }
            </div>
        )
    }
}
