// Angular/primerangular/src/app/components/tablamultiplicar/tablamultiplicar.component.ts
import { Component, ViewChild, ElementRef } from '@angular/core';

@Component({
  selector: 'app-tablamultiplicar',
  templateUrl: './tablamultiplicar.component.html',
  styleUrl: './tablamultiplicar.component.css'
})
export class TablamultiplicarComponent {
  @ViewChild("cajanumero") cajaNumeroRef!: ElementRef;
  // public tabla: { 
  //   operacion: string; 
  //   resultado: number 
  // }[] = [];
  public tabla: Array<number>;
  public numero: number;
  constructor() {
    this.tabla = new Array<number>();
    this.numero = 0;
  }

  mostrarTabla(): void {
    this.tabla = [];
    this.numero = this.cajaNumeroRef.nativeElement.value;
    for (let i = 0; i <= 10; i++) {
      //let operacion = num + "*" + i
      let resultado = this.numero * i;
      //this.tabla.push({ operacion, resultado });
      this.tabla.push(resultado);
    }
  }
}

<div>
    <h1>TABLA MULTIPLICAR</h1>
    <form #tablaMultiplicar="ngForm">
        <label>Número: </label>
        <input type="number" name="cajanumero" #cajanumero /><br />
        <button type="button" (click)="mostrarTabla()">Mostrar tabla</button>
        <table border="1" *ngIf="tabla.length > 0">
            <thead>
                <tr>
                    <th>Operación</th>
                    <th>Resultado</th>
                </tr>
            </thead>
            <tbody>
                <!-- <tr *ngFor="let fila of tabla">
                    <td>{{ fila.operacion }}</td>
                    <td>{{ fila.resultado }}</td>
                </tr> -->
                <tr *ngFor="let fila of tabla; let i = index">
                    <td>{{ numero }} * {{ i }}</td>
                    <td>{{ fila }}</td>
                </tr>
            </tbody>
        </table>
    </form>
</div>

// React/reactformsrutas/src/components/TablaMultiplicar.js
import React, { Component } from 'react'

export default class TablaMultiplicar extends Component {
    cajaNumero = React.createRef();
    state = {
        array: []
    }
    formulario = (e) => {
        e.preventDefault();
        let numero = parseInt(this.cajaNumero.current.value);
        var nuevoArray = []

        for (let i = 0; i <= 10; i++) {
            nuevoArray.push({
                operacion: numero + "*" + i,
                resultado: numero * i
            })
            // Otra solución sería hacer el push
            // con las td directamente, y en el map
            // únicamente hacer return de 'fila'
        }

        this.setState({
            array: nuevoArray
        })
    }
    render() {
        return (
            <div>
                <h1>Tabla de Multiplicar</h1>
                <form onSubmit={this.formulario}>
                    <label>Número</label>
                    <input type="text" ref={this.cajaNumero}></input>
                    <button>Ver tabla</button>
                </form>
                <table>
                    <thead>
                        <tr>
                            <th>Operación</th>
                            <th>Resultado</th>
                        </tr>
                    </thead>
                    <tbody>
                        {
                            this.state.array.map((fila, index) => (
                                <tr key={index}>
                                    <td>{fila.operacion}</td>
                                    <td>{fila.resultado}</td>
                                </tr>
                            ))
                        }
                    </tbody>
                </table>
            </div>
        )
    }
}
