// Vue/vuealumnos/src/components/LoginComponent.vue
<template>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="card shadow-sm">
          <div class="card-body">
            <h3 class="card-title text-center mb-4">Iniciar Sesión</h3>
            <form v-on:submit.prevent="iniciarSesion()">
              <div class="mb-3">
                <label for="usuario" class="form-label">Usuario</label>
                <input
                  type="text"
                  v-model="login.userName"
                  class="form-control"
                />
              </div>
              <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input
                  type="password"
                  v-model="login.password"
                  class="form-control"
                />
              </div>
              <div class="d-grid gap-2">
                <button class="btn btn-success">Iniciar Sesión</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import ServiceAlumnos from "./../services/ServiceAlumnos";
const service = new ServiceAlumnos();
export default {
  name: "LoginComponent",
  methods: {
    iniciarSesion() {
      service.postAuth(this.login).then((result) => {
        console.log("Valor: " + result.data.response);
        service.setToken(result.data.response);
        console.log("Token guardado");
        this.$router.push("/alumnostoken");
      });
    },
  },
  data() {
    return {
      login: {
        userName: "",
        password: "",
      },
    };
  },
};
</script>

<style></style>

// Angular/angularalumnos/src/app/components/login/login.component.ts
import { Component, ViewChild, ElementRef } from '@angular/core';
import { ServiceAlumnos } from '../../services/service.alumnos';
import { Router } from '@angular/router';
import { environment } from '../../../environments/environment.development';
import { Login } from '../../models/login';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  @ViewChild("cajausuario") cajaUsuario!: ElementRef;
  @ViewChild("cajapassword") cajaPassword!: ElementRef;

  constructor(
    private _service: ServiceAlumnos,
    private _router: Router
  ) { }

  iniciarSesion() {
    let userName = this.cajaUsuario.nativeElement.value;
    let password = this.cajaPassword.nativeElement.value;

    let login = new Login(userName, password);
    this._service.postAuth(login).subscribe(response => {
      for (let key in response) {
        console.log("Valor: " + response[key]);
        if (response[key]) {
          this._service.setToken(response[key]);
          console.log("Token guardado");
          this._router.navigate(['/alumnos']);
        }
      }
    })
  }
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Iniciar Sesión</h3>
                    <form #createForm="ngForm">
                        <div class="mb-3">
                            <label for="usuario" class="form-label">Usuario</label>
                            <input type="text" id="usuario" class="form-control" name="cajausuario" #cajausuario />
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" id="password" class="form-control" name="cajapassword" #cajapassword />
                        </div>
                        <div class="d-grid gap-2">
                            <button class="btn btn-success" (click)="iniciarSesion()">Iniciar Sesión</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
