// Angular/serviciosangular/src/app/components/comic/comic.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Comic } from '../../models/comic';

@Component({
  selector: 'app-comic',
  templateUrl: './comic.component.html',
  styleUrl: './comic.component.css'
})
export class ComicComponent {
  @Input() comic!: Comic;
  @Output() seleccionarFavoritoPadre: EventEmitter<any> = new EventEmitter();

  seleccionarFavoritoHijo(): void {
    this.seleccionarFavoritoPadre.emit(this.comic);
  }
}

<div>
    <h1>Título: {{ comic.titulo }}</h1>
    <img [src]=comic.imagen  style="width: 200px; height: 150px"/>
    <h3>{{ comic.pieImagen }}</h3>
    <button (click)="seleccionarFavoritoHijo()">Seleccionar cómic favorito</button>
</div>

// React/reactclases/src/components/Comic.js
import { Component } from "react";

class Comic extends Component {
    render() {
        return (
            <div>
                <h1>{this.props.comic.titulo}</h1>
                <p>{this.props.comic.descripcion}</p>
                <img src={this.props.comic.imagen} style={{ width: "250px", height: "350px" }}></img>
                <button onClick={() => {
                    this.props.seleccionarFavorito(this.props.comic);
                }}>
                    Seleccionar favorito</button>
                <button onClick={() => {
                    this.props.eliminarComic(this.props.index);
                }}>
                    Eliminar cómic</button>
            </div>
        )
    }
}

export default Comic;
