// Vue/vuecomunicacioncomponents/src/components/ComicComponent.vue
<template>
  <div>
    <h2>{{ comic.titulo }}</h2>
    <p>{{ comic.descripcion }}</p>
    <img :src="comic.imagen" />
    <h4
      :class="{
        rojo: comic.year <= 2000,
        verde: comic.year > 2000,
      }"
    >
      Año: {{ comic.year }}
    </h4>
    <button @click="seleccionarFavorito()">Seleccionar favorito</button>
    <button class="rojo" @click="deleteComic()">Delete</button>
  </div>
</template>

<script>
export default {
  name: "ComicComponent",
  props: ["comic", "index"],
  methods: {
    seleccionarFavorito() {
      this.$emit("seleccionarFavorito", this.comic);
    },
    deleteComic() {
      this.$emit("deleteComic", this.index);
    },
  },
};
</script>

<style>
@import "./../assets/css/estilocomic.css";
</style>

// React/reactclases/src/components/Comic.js
import { Component } from "react";

class Comic extends Component {
    render() {
        return (
            <div>
                <h1>{this.props.comic.titulo}</h1>
                <p>{this.props.comic.descripcion}</p>
                <img src={this.props.comic.imagen} style={{ width: "250px", height: "350px" }}></img>
                <button onClick={() => {
                    this.props.seleccionarFavorito(this.props.comic);
                }}>
                    Seleccionar favorito</button>
                <button onClick={() => {
                    this.props.eliminarComic(this.props.index);
                }}>
                    Eliminar cómic</button>
            </div>
        )
    }
}

export default Comic;
