// Angular/primerangular/src/app/components/tablamultiplicar/tablamultiplicar.component.ts
import { Component, ViewChild, ElementRef } from '@angular/core';

@Component({
  selector: 'app-tablamultiplicar',
  templateUrl: './tablamultiplicar.component.html',
  styleUrl: './tablamultiplicar.component.css'
})
export class TablamultiplicarComponent {
  @ViewChild("cajanumero") cajaNumeroRef!: ElementRef;
  // public tabla: { 
  //   operacion: string; 
  //   resultado: number 
  // }[] = [];
  public tabla: Array<number>;
  public numero: number;
  constructor() {
    this.tabla = new Array<number>();
    this.numero = 0;
  }

  mostrarTabla(): void {
    this.tabla = [];
    this.numero = this.cajaNumeroRef.nativeElement.value;
    for (let i = 0; i <= 10; i++) {
      //let operacion = num + "*" + i
      let resultado = this.numero * i;
      //this.tabla.push({ operacion, resultado });
      this.tabla.push(resultado);
    }
  }
}

<div>
    <h1>TABLA MULTIPLICAR</h1>
    <form #tablaMultiplicar="ngForm">
        <label>Número: </label>
        <input type="number" name="cajanumero" #cajanumero /><br />
        <button type="button" (click)="mostrarTabla()">Mostrar tabla</button>
        <table border="1" *ngIf="tabla.length > 0">
            <thead>
                <tr>
                    <th>Operación</th>
                    <th>Resultado</th>
                </tr>
            </thead>
            <tbody>
                <!-- <tr *ngFor="let fila of tabla">
                    <td>{{ fila.operacion }}</td>
                    <td>{{ fila.resultado }}</td>
                </tr> -->
                <tr *ngFor="let fila of tabla; let i = index">
                    <td>{{ numero }} * {{ i }}</td>
                    <td>{{ fila }}</td>
                </tr>
            </tbody>
        </table>
    </form>
</div>

// Vue/vuepracticaslunes/src/components/TablaMultiplicar.vue
<template>
  <div>
    <label>Tabla Multiplicar</label>
    <button @click="generarTablaBoton()">Generar Tabla Botón</button>
    <input type="number" v-model="numero" />
    <!-- Tabla generada usando el botón -->
    <table border="1">
      <thead>
        <tr>
          <th>Operación</th>
          <th>Resultado</th>
        </tr>
      </thead>
      <tbody v-html="html"></tbody>
    </table>
    <!-- Tabla generada usando directivas -->
    <table border="1">
      <thead>
        <tr>
          <th>Operación</th>
          <th>Resultado</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="num in 11" :key="num">
          <td style="text-align: center; color: red">
            {{ numero + "*" + (num - 1) }}
          </td>
          <td style="text-align: center; color: green">
            {{ numero * (num - 1) }}
          </td>
        </tr>
      </tbody>
    </table>
    <!-- Tabla generada usando filtros -->
    <table border="1">
      <thead>
        <tr>
          <th>Operación</th>
          <th>Resultado</th>
        </tr>
      </thead>
      <tbody>
        <!-- <tr
          v-for="(operacion, index) in $filters.getOperacion(numero)"
          :key="index"
        >
          <td style="text-align: center; color: blue">{{ operacion }}</td>
          <td style="text-align: center; color: purple">
            {{ $filters.getMultiplicacion(numero)[index] }}
          </td>
        </tr> -->
        <tr v-for="contador in 11" :key="contador">
            <td style="text-align: center; color: blue">{{$filters.getOperacion(numero, (contador - 1))}}</td>
            <td style="text-align: center; color: purple">{{$filters.getMultiplicacion(numero, (contador - 1))}}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
export default {
  name: "TablaMultiplicar",
  methods: {
    generarTablaBoton() {
      this.html = "";
      for (let i = 0; i <= 10; i++) {
        this.operacion = this.numero + "*" + i;
        this.resultado = this.numero * i;
        this.html += "<tr>";
        this.html +=
          "<td style='text-align: center; color: orange;'>" +
          this.operacion +
          "</td>";
        this.html +=
          "<td style='text-align: center; color: black;'>" +
          this.resultado +
          "</td>";
        this.html += "</tr>";
      }
    },
  },
  data() {
    return {
      html: "",
      numero: 0,
      operacion: "",
      resultado: 0,
    };
  },
};
</script>

<style></style>
