// Vue/vueservicios/src/components/MenuComponent.vue
<template>
  <div>
    <nav
      class="navbar navbar-expand-sm navbar-dark bg-dark"
      aria-label="Third navbar example"
    >
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Vue Servicios</a>

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarsExample03"
          aria-controls="navbarsExample03"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample03">
          <ul class="navbar-nav me-auto mb-2 mb-sm-0">
            <li class="nav-item">
              <router-link class="nav-link active" aria-current="page" to="/"
                >Home</router-link
              >
            </li>

            <li class="nav-item">
              <router-link class="nav-link" to="/coche">Coches</router-link>
            </li>

            <li class="nav-item">
              <router-link class="nav-link" to="/customers"
                >Customers</router-link
              >
            </li>

            <li class="nav-item">
              <router-link class="nav-link" to="/empleadosdetalle"
                >Empleados detalle</router-link
              >
            </li>

            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                >Oficios</a
              >

              <ul class="dropdown-menu">
                <li v-for="ofi in oficios" :key="ofi">
                  <router-link
                    class="dropdown-item"
                    :to="'/empleadosoficios/' + ofi"
                  >
                    {{ ofi }}
                  </router-link>
                </li>
              </ul>
            </li>
          </ul>

          <form role="search">
            <input
              class="form-control"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
          </form>
        </div>
      </div>
    </nav>
  </div>
</template>

<script>
import ServiceEmpleados from './../services/ServiceEmpleados';
const service = new ServiceEmpleados();

export default {
  name: "MenuComponent",
  data() {
    return {
      oficios: [],
    };
  },
  mounted() {
    service.getOficios().then(result => {
        this.oficios = result;
    })
  },
};
</script>

// Angular/serviciosangular/src/app/components/menu/menu.component.ts
import { Component} from '@angular/core';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrl: './menu.component.css'
})
export class MenuComponent{

  constructor() {

  }

}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" [routerLink]="['/']">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/libreria']">Comics</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/coches']">Coches</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/plantilla']">Plantilla simple</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/plantillamultiple']">Plantilla múltiple</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" [routerLink]="['']">Action</a>
            </li>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <!-- <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
    </div>
  </div>
</nav>
