// Angular/angularempleadosauth/src/app/components/perfilempleado/perfilempleado.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import { ServiceEmpleados } from '../../services/service.empleados';
import { Empleado } from '../../models/empleado';

@Component({
  selector: 'app-perfilempleado',
  templateUrl: './perfilempleado.component.html',
  styleUrl: './perfilempleado.component.css'
})
export class PerfilempleadoComponent implements OnInit{
  public empleado!: Empleado;
  constructor(
    private _service: ServiceEmpleados,
  ){}


  cargarPerfil() {
    this._service.getPerfilEmpleado().subscribe(response => {
      console.log("La respuesta es: " + JSON.stringify(response))
      this.empleado = response;
    })
  }

  ngOnInit(): void {
    this.cargarPerfil();
  }

}

<app-menu></app-menu>
<div>
    <h1>Perfil Empleado</h1>
    <button class="btn btn-primary" [routerLink]="['/']">Volver a inicio de sesión</button>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id Empleado</th>
                <th>Apellido</th>
                <th>Oficio</th>
                <th>Salario</th>
                <th>Director</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngIf="empleado">
                <td>{{ empleado.idEmpleado }}</td>
                <td>{{ empleado.apellido }}</td>
                <td>{{ empleado.oficio }}</td>
                <td>{{ empleado.salario }}</td>
                <td>{{ empleado.director }}</td>
            </tr>
        </tbody>
    </table>
</div>

// Vue/vueempleadosauth/src/components/PerfilEmpleadoComponent.vue
<template>
  <div>
    <MenuComponent />
    <div>
      <h1>Perfil Empleado</h1>
      <router-link to="/" class="btn btn-danger" @click="cerrarSesion">
        Cerrar Sesión
      </router-link>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Id Empleado</th>
            <th>Apellido</th>
            <th>Oficio</th>
            <th>Salario</th>
            <th>Director</th>
          </tr>
        </thead>
        <tbody>
          <tr v-if="empleado">
            <td>{{ empleado.idEmpleado }}</td>
            <td>{{ empleado.apellido }}</td>
            <td>{{ empleado.oficio }}</td>
            <td>{{ empleado.salario }}</td>
            <td>{{ empleado.director }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import MenuComponent from "./MenuComponent.vue";
import ServiceEmpleados from "./../services/ServiceEmpleados";
const service = new ServiceEmpleados();
export default {
  name: "PerfilEmpleadoComponent",
  components: {
    MenuComponent,
  },
  methods: {
    getPerfilEmpleado() {
      service.getPerfilEmpleado().then((result) => {
        this.empleado = result;
      });
    },
    cerrarSesion() {
      service.cerrarSesion();
    }
  },
  data() {
    return {
      empleado: {},
    };
  },
  mounted() {
    this.getPerfilEmpleado();
  },
  watch: {
    '$route.path': function () {
      this.getPerfilEmpleado();
    }
  },
};
</script>

<style></style>
