// Angular/angularempleadosauth/src/app/components/subordinadosempleado/subordinadosempleado.component.ts
import { Component } from '@angular/core';
import { ServiceEmpleados } from '../../services/service.empleados';
import { Empleado } from '../../models/empleado';

@Component({
  selector: 'app-subordinadosempleado',
  templateUrl: './subordinadosempleado.component.html',
  styleUrl: './subordinadosempleado.component.css'
})
export class SubordinadosempleadoComponent {
  public empleados!: Array<Empleado>;
  constructor(
    private _service: ServiceEmpleados,
  ){}

  cargarSubordinados() {
    this._service.getSubordinados().subscribe(response => {
      console.log("La respuesta Subordinados es: " + JSON.stringify(response))
      this.empleados = response;
    })
  }

  ngOnInit(): void {
    this.cargarSubordinados();
  }
}

<app-menu></app-menu>
<div>
    <h1>Subordinados Empleado</h1>
    <button class="btn btn-primary" [routerLink]="['/']">Volver a inicio de sesión</button>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id Empleado</th>
                <th>Apellido</th>
                <th>Oficio</th>
                <th>Salario</th>
                <th>Director</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let empleado of empleados">
                <td>{{ empleado.idEmpleado }}</td>
                <td>{{ empleado.apellido }}</td>
                <td>{{ empleado.oficio }}</td>
                <td>{{ empleado.salario }}</td>
                <td>{{ empleado.director }}</td>
            </tr>
        </tbody>
    </table>
</div>

// Vue/vueempleadosauth/src/components/SubordinadosEmpleadoComponent.vue
<template>
  <div>
    <MenuComponent />
    <div>
      <h1>Subordinados Empleado</h1>
      <router-link to="/" class="btn btn-danger" @click="cerrarSesion">
        Volver a inicio de sesión
      </router-link>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Id Empleado</th>
            <th>Apellido</th>
            <th>Oficio</th>
            <th>Salario</th>
            <th>Director</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="empleado of empleados" :key="empleado">
            <td>{{ empleado.idEmpleado }}</td>
            <td>{{ empleado.apellido }}</td>
            <td>{{ empleado.oficio }}</td>
            <td>{{ empleado.salario }}</td>
            <td>{{ empleado.director }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import MenuComponent from "./MenuComponent.vue";
import ServiceEmpleados from "./../services/ServiceEmpleados";
const service = new ServiceEmpleados();
export default {
  name: "PerfilEmpleadoComponent",
  components: {
    MenuComponent,
  },
  methods: {
    getSubordinados() {
      service.getSubordinados().then((result) => {
        this.empleados = result;
      });
    },
    cerrarSesion() {
      service.cerrarSesion();
    }
  },
  data() {
    return {
      empleados: [],
    };
  },
  mounted() {
    this.getSubordinados();
  },
  watch: {
    '$route.path': function () {
      this.getSubordinados();
    }
  },
};
</script>

<style></style>
