// React/reactclases/src/components/HijoNumero.js
import { Component } from "react";

class HijoNumero extends Component {
    sumarNumero = () => {
        var numero = parseInt(this.props.numero);
        this.props.mostrarSuma(numero);
    }
    render() {
        return (
            <div>
                <h2>El número es {this.props.numero}</h2>
                <button onClick={this.sumarNumero}>Sumar {this.props.numero}</button>
            </div>
        )
    }
}

export default HijoNumero;

// Vue/vuecomunicacioncomponents/src/components/HijoNumero.vue
<template>
  <div>
    <h1 style="color: blue">Número hijo: {{ numero }}</h1>
    <button @click="sumar()">Sumar {{ numero }}</button>
  </div>
</template>

<script>
export default {
  name: "HijoNumero",
  props: ["numero"],
  methods: {
    sumar() {
      this.$emit("mostrarSuma", this.numero);
    },
  },
};
</script>

<style></style>
